### ISSUE TITLE
Missing read_merger.pl with --paired option

### ISSUE THREAD

**Issue by papanikos** [fbreitwieser/krakenhll#11]
Hello,

I have a pair of fastq read files that I would like to run with krakenhll.
At first I missed the `--paired` option, but everything run fine (just got 2x the actual input number).
When I included the `--paired` option I got this
```
Can't exec "read_merger.pl": No such file or directory at /tools/krakenhll/krakenhll line 253.
krakenhll: can't exec read_merger.pl: No such file or directory
```
I do have a **krakenhll**-read_merger.pl in my installation directory, though.

Regards,
Nikos

**Comment by fbreitwieser** [comment]
Hi Nikos, I just fixed this a couple minutes ago ;). Slipped my attention because I had a `read_merger.pl` script in my global path. Can you try again with the latest Github version?

**Comment by fbreitwieser** [comment]
Feel free to reopen if the problem persists
