### ISSUE TITLE
Refactor `krakenhll-report` to use `taxDB` [edit]

### ISSUE THREAD

**Issue by zhaoc1** [fbreitwieser/krakenhll#14]
Hi Florian,

I encountered some inconsistent read counts when using `krakenhll --report-file report1.tsv --output raw.tsv ...` and `krakenhll-report raw.tsv > report2.tsv`. 

For example, the following lines are from **report2.tsv**

 65.23	1447217	1447217	U	0	unclassified
 21.57	478536	0	-	1	root
 21.57	478536	0	D	10239	  Viruses
 21.57	478536	0	-	439488	    ssRNA viruses
 21.57	478536	0	-	35278	      ssRNA positive-strand viruses, no DNA stage
 21.57	478536	0	F	11974	        Caliciviridae
 21.57	478536	0	G	95341	          Sapovirus
 21.57	**478536**	0	S	**95342**	            Sapporo virus
 21.57	478536	478536	-	515176	              Sapovirus GI

While the correponding species from the **report1.tsv** are:

34.74	770849	0	4254	1.02e+04	0.05336	95341	genus	          Sapovirus
34.74	**770849**	0	4252	1.02e+04	0.06558	**95342**	species	            Sapporo virus

The same taxID 95342 got different **reads counts** (2nd col).

Any thought? Thanks.

Best,
Chunyu

**Comment by zhaoc1** [comment]
@fbreitwieser  `dump_taxdb` fixed the discrepancy. YAY! Thank you very much!

**Comment by fbreitwieser** [comment]
Glad to hear that! I'll leave the issue open until I updated `krakenhll-report` to use `taxDB`.

**Comment by zhaoc1** [comment]
sure :)
