### ISSUE TITLE
Error Running krakenhll-mpa-report

### ISSUE THREAD

**Issue by dcdanko** [fbreitwieser/krakenhll#15]
Hiya,

When I run `krakenhll-mpa-report` I get the following error:

`krakenhll-mpa-report: can't open names file: No such file or directory`

Any easy fix?

**Comment by dcdanko** [comment]
Hey, should have mentioned it sooner but I ended up making my own script that makes an MPA with parameters for minimum kmers and coverage. If it's useful it's yours.

https://github.com/MetaSUB/MetaSUB_CAP/blob/master/scripts/parse_krakenhll.py

**Comment by fbreitwieser** [comment]
Nice idea and work! I probably will copy the ideas from your script over to Perl as most of the other scripts are in Perl. I'll add a new issue for that.
