### ISSUE TITLE
Error in extracting reads in FASTQ format 

### ISSUE THREAD

**Issue by zhaoc1** [fbreitwieser/krakenhll#17]
Hi,

I find the `krakenhll-extract-reads` super useful, and I had no problem extracting reads in FASTA format. Yet when I ask for reads in FASTQ format, I got many WARNING messages as following:

"Use of uninitialized value $_ in print at /home/chunyu/bin/krakenhll-extract-reads line 189, <$FQ> line 11189093."

```bash
krakenhll-extract-reads -p -t mykrakenHLLDB/taxDB taxid raw/sample-raw.tsv reads/sample_%.fastq > sample.fastq
```

And by looking at the generated `sample.fastq` file (head -12):

ATTTATAGCTTTTAAAAGATCTTGTCTTAATCTTGAGAATAAAATTGTTATGGAGCTTGGGTATTTAATGACAGATGATGATATGAGAAGGGATGTTAAATCTAAGATACATAACCTTGTTATAAT
+
A:>>ADGEGGGEGGEFFGGEGGCGGGGGGGGGGGGEGGEGGGGCGG1CF=BFGEBGGCG/@FGGGFCGGFFFF>FGGFGGGGDGGGGEGEB>FGGGFEDCG@0EFCDGGF:FE:=:==@GE>@FB0
@D00728:58:CC9MGANXX:4:2310:6670:2239 2:N:0:ACTGAGCG+AAGGAGTA
CATCAAAATTACCCTTAGATATATTGTTAAGTGCAGTTATAACAAGGTTATGTATCTTAGATTTAACATCCCTTCTCATATCATCATCTGTCATTAAATACCCAAGCTCAATAACAATTTTATTCT
+
CCBBCGGFGG>D@;FGC>FGGEFGGGGGGG>@F>DGECGGGGGEGEG1>:FGGGDGFGGGGGGC@>111<:0?:10<1=11;110:=0==:00F0;E000;=0ED00::0=:E00=0@CC0;;@00
TTTATATTATTTGAGAGTAAAAGGTGGCGATAGGTTTAAGGTTTATTCTATGTTTATAAAACCTTTAATTCCTAAAGGGAGTATTTATGTAGGCGATTTAAATAATAAAGGTATGGATCCTGTCTC
+
?@@@BGGGGGGFGGGGGCGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGCFGGGGGGGGGFGGGGGGGGGGGGGGGGGGGEGGFGGGGGGGGGGFGGGGGGGEG@
@D00728:58:CC9MGANXX:4:2310:8691:2163 2:N:0:ACTGAGCG+AAGGAGTA
GATCCATACCTTTATTATTTAAATCGCCTACATAAATACTCCCTTTAGGAATTAAAGGTTTTATAAACATAGAATAAACCTTAAACCTATCGCCACCTTTTACTCTCAAATAATATAAACTGTCTC

The header line for the first read is missing, so is the third read. It seems like the interleaved PE reads is bad formatted.

Any ideas what went wrong? Thank you!

Best,
Chunyu

**Comment by fbreitwieser** [comment]
Hi Chunyu, should be fixed now. I was working on supporting multiline FASTAs recently and had introduced a bug for FASTQ extraction then. Please try again, and let me know if it doesn't work.
Florian

**Comment by zhaoc1** [comment]
It works 👍🏻
