### ISSUE TITLE
brew install g++ (no formulae found in taps)

### ISSUE THREAD

**Issue by gputzel** [fbreitwieser/krakenhll#19]
When I try

`brew install g++`

as suggest in `README` I get:

`Error: No formulae found in taps.`

This is on Mac OS X 10.13.5, with Homebrew 1.6.9.

**Comment by fbreitwieser** [comment]
Please try 
```
brew install gcc
```
I'll fix the documentation

**Comment by gputzel** [comment]
`brew install gcc`

worked without problems, but then I don't have anything called `g++-7` as in `README`.  I do have `g++-4.9` (probably from a different installation), `g++-5`, and `g++-8`.

**Comment by fbreitwieser** [comment]
Great, I'll updated the README to refer to g++-8
