### ISSUE TITLE
questions

### ISSUE THREAD

**Issue by FCMicrobes** [fbreitwieser/krakenhll#2]
Hello,
Thanks again for suggesting this tool. 
This is not to report an issue but to ask questions regarding krakenhll.

I have been running ```krakenhll``` on a few sample using viral and archaea refseq db (processed with ```build_taxdb``` to generate ```taxDB```) using the following command:
```
krakenhll \
--db /bank/kraken/RefSeq/krakenDB/viral \
--db /bank/kraken/RefSeq/krakenDB/archaea \
--preload \
--threads $NSLOTS --fastq-input --gzip-compressed \
--paired $INPUT$NAME*'_R1'*'fastq'* $INPUT$NAME*'_R2'*'fastq'* \
--report-file $OUT$NAME'_krakenhll_report.tsv' > $OUT$NAME'_krakenhll_output.tsv'
```
1- During the processing I got this informations:

```
Tue Dec  5 18:43:59 CET 2017
/gs7k1/binaries/krakenhll/0.1.1/classify -d /bank/kraken/centrifuge/RefSeq/AUTO/krakenDB/viral/database.kdb -d /bank/kraken/centrifuge/RefSeq/AUTO/krakenDB/archaea/database.kdb -i /bank/kraken/centrifuge/RefSeq/AUTO/krakenDB/viral/database.idx -i /bank/kraken/centrifuge/RefSeq/AUTO/krakenDB/archaea/database.idx -t 20 -M -r krakenhll_test/ESw5INH24_krakenhll_report.tsv -a /bank/kraken/centrifuge/RefSeq/AUTO/krakenDB/viral/taxDB -p 12 /dev/fd/0
Loading database(s)...
 Database /bank/kraken/centrifuge/RefSeq/AUTO/krakenDB/viral/database.kdb
Loaded database with 192643959 keys with k of 31 [val_len 4, key_len 8].
 Database /bank/kraken/centrifuge/RefSeq/AUTO/krakenDB/archaea/database.kdb
Loaded database with 1038638119 keys with k of 31 [val_len 4, key_len 8].

complete.
Reading taxonomy index from /bank/kraken/centrifuge/RefSeq/AUTO/krakenDB/viral/taxDBCannot find parent for 0
. Done, read 1660864 taxa.
Writing Kraken report output to krakenhll_test/ESw5INH24_krakenhll_report.tsv
Processed 1000000 sequences (9813 classified) ...Finishing up ..
1000000 sequences (469.63 Mbp) processed in 23.725s (2528.9 Kseq/m, 1187.67 Mbp/m).se.kdb.countsReading genome sizes from /bank/kraken/centrifuge/RefSeq/AUTO/krakenDB/archaea/database.kdb.counts
  9813 sequences classified (0.98%)
  990187 sequences unclassified (99.02%)
```
I only had this message for one of the two DBs I have specified :  ```Reading taxonomy index from /bank/kraken/centrifuge/RefSeq/AUTO/krakenDB/viral/taxDB```

I also got : ```Reading genome sizes from /bank/kraken/centrifuge/RefSeq/AUTO/krakenDB/archaea/database.kdb.counts``` only for archaea DB.
Is it expected?

2- According to the github, krakenhll should report 8 columns, I got 9: 
```
%       reads   taxReads        kmers   dup     cov     taxID   rank    taxName
99.08   990791  990791  349731445       1.17    NA      0       no rank unclassified
0.9209  9209    0       47350   1.96    4.544e-05       1       no rank root
0.8773  8773    0       43831   1.98    4.206e-05       131567  no rank   cellular organisms
0.8773  8773    55      43831   1.98    4.206e-05       2157    superkingdom        Archaea
0.8383  8383    101     40963   1.71    4.38e-05        28890   phylum        Euryarchaeota
0.6569  6569    747     30799   1.43    5.622e-05       183963  class           Halobacteria
0.2435  2435    85      10206   1.32    4.847e-05       1644055 order             Haloferacales
0.149   1490    68      5681    1.39    5.224e-05       1963271 family              Halorubraceae
0.0896  896     371     3346    1.39    4.358e-05       56688   genus                 Halorubrum
0.0037  37      37      99      1.42    4.197e-05       1419722 species                 Halorubrum sp. SD626R
0.0034  34      34      144     1.16    6.174e-05       1765655 species                 Halorubrum tropicale
0.0034  34      34      111     1.29    4.793e-05       1758255 species                 Halorubrum sp. SAH-A6
0.0032  32      32      97      1.95    3.076e-05       2247    species                 Halorubrum lacusprofundi
0.0028  28      28      62      1.29    3.575e-05       1194088 species                 Halorubrum sp. T3
0.0026  26      0       98      1.37    4.215e-05       368624  species                 Halorubrum lipolyticum
0.0026  26      26      98      1.37    4.215e-05       1227482 no rank                   Halorubrum lipolyticum DSM 21995
```
Could you help me to understand what the columns represent?

3- Do you have any guidelines, advices to filter this report in order to increase sensitivity? Is there any command to do it within krakenhll?

4- Is there any advantage to run Bracken on krakenhll output?

5- The ability to export or merge reports into one biom table will be really awesome. I have tried kraken-biom but it gave me the following error : 

```
Traceback (most recent call last):
File "/usr/local/bioinfo/kraken-biom/1.0.1a/venv/bin/kraken-biom", line 11, in
sys.exit(main())
File "/gs7k1/binaries/kraken-biom/1.0.1a/venv/lib/python3.4/site-packages/kraken_biom.py", line 377, in main
biomT = create_biom_table(sample_counts, taxa)
File "/gs7k1/binaries/kraken-biom/1.0.1a/venv/lib/python3.4/site-packages/kraken_biom.py", line 196, in create_biom_table
generated_by=gen_str, input_is_dense=True)
File "/gs7k1/binaries/kraken-biom/1.0.1a/venv/lib/python3.4/site-packages/biom/table.py", line 397, in init
errcheck(self)
File "/gs7k1/binaries/kraken-biom/1.0.1a/venv/lib/python3.4/site-packages/biom/err.py", line 472, in errcheck
raise ret
biom.exception.TableException: Number of sample IDs differs from matrix size!
```

Thanks !

**Comment by fbreitwieser** [comment]
Hi @FCMicrobes , thanks for trying it out! 

Re 1: For hierarchical mapping with multiple databases, all taxonomies have to be the same, thus only one is loaded. I explicitly check this, now. There was a bug, however, with the counts table - only the last was read and used. Should be fixed now.

Re 2: The new columns are 'kmers', 'dup', and 'cov'. 'kmers' is the number of unique k-mer for the clades seen in reads, 'dup' is the average duplicity of k-mers, i.e. how often did each of the unique k-mers appear, and 'cov' is the proportion of all the k-mers that are in the database that have been observed.

Re 3: The threshold depends on your application, similar to a read count threshold you might choose. 

Re 4: Bracken will run exactly the same on Kraken and KrakenHLL output, currently.

Re 5: You can get rid of the header and the k-mer columns using the following commands:

    tail -n +2 REPORT | cut -f 1-3,7-10

However, the rank column still is different. Let's see if kraken-biom will support krakenhll directly or otherwise I can make a change to have a more Kraken-y output.

**Comment by fbreitwieser** [comment]
Let me know if you have any further questions.

**Comment by Johnsonzcode** [comment]
Sorry to reopen this thread.
May I ask the meaning of `taxReads` in question 2 ?
