### ISSUE TITLE
adding additional data to database build directory

### ISSUE THREAD

**Issue by Krischan** [fbreitwieser/krakenhll#21]
I'd like to add a couple of genomes to a database build directory. My understanding is to add the FA files to the`library/`folder and provide a `seqid2taxid.map` file.

1. Can the additional FA data be placed in a subfolder of `library/` ?
2. Should the `seqid2taxid.map` file be appended to an existing `seqid2taxid.map` file?

I figured I ask here, since trial and error would be a bit tedious when building the `nt` database.

**Comment by fbreitwieser** [comment]
Hi Krischan,
You can put both the FASTA files as well as the mapping files inside the library folder. However, you should remove the `DB/seqid2taxid.map` file in the main folder first, or move it into the `DB/library/` folder. The reason for this is that KrakenHLL combines all `.map` files inside the `DB/library/` folder into the `DB/seqid2taxid.map` file, but only if it does not exist.
Hope that helps!
