### ISSUE TITLE
verify_gi_numbers.pl and cp_into_tempfile.pl

### ISSUE THREAD

**Issue by PhDstuff** [fbreitwieser/krakenhll#5]
Both files are not downloaded in the zip file for krakenhll installation.
When performing:
scripts/krakenhll-build --add-to-library genome.fasta --db db
This was found

**Comment by fbreitwieser** [comment]
Hi @PhDstuff , thanks for reporting the issue. Note that the `--add-to-library` mostly just copies `genome.fasta` into the directory `db/library`, and you may do that manually. Note that you need a `seqid2taxid.map` that lists the sequence ID to taxonomy ID, tab separated, for each sequence. Different to previous versions of Kraken the sequence ID is the header up to the first space.

**Comment by PhDstuff** [comment]
For the seqid2taxid.map file, do these need to be actual taxid ID's
I have multiple genomes from the same species (different strains) and want to try distinguish between them. How do I seperate them for identification?
I tried using:
krakenhll-build --generate-taxonomy-ids-for-sequences
But this did not appear to work (was not accepted as an option). I tried adding the option '--taxids-for-genomes' but this appeared to not have any effect

**Comment by fbreitwieser** [comment]
`seqid2taxid.map` needs taxonomy IDs that are in the `taxDB` file - which by default is built from the NCBI taxonomy. You could make a custom `taxDB`, but alternatively you can also just rely on the `--taxids-for-genomes` and `--taxids-for-sequences` parameters (the `README` has the wrong arguments there, will fix that). 

Consider having the following sequences from the same species Blu w/ taxid 8888
```
>Strain1_Chr1
>Strain1_Chr2
>Strain1_Plasmid1
>Strain2_Chr1 
>Strain2_Plasmid1 
```

The `seqid2taxid.map` should look like that:
```
Strain1_Chr1 <tab> 8888 <tab> Blu Strain 1
Strain1_Chr2 <tab> 8888 <tab> Blu Strain 1
Strain1_Plasmid1 <tab> 8888 <tab> Blu Strain 1
Strain2_Chr1  <tab> 8888 <tab> Blu Strain 2
Strain2_Plasmid1 <tab> 8888 <tab> Blu Strain 2
```

Running `krakenhll-build --taxids-for-genomes --taxids-for-sequences` adds taxonomy nodes below 8888 for the two strains:
```
-Blu, taxid 8888, rank species 
-- Blu Strain 1, taxid 100000001, rank assembly
--- Strain1_Chr1, taxid 100000002, rank sequence
--- Strain1_Chr2, taxid 100000003, rank sequence
--- Strain1_Plasmid1, taxid 100000004, rank sequence
-- Blu Strain 2, taxid 100000005, rank assembly
--- Strain2_Chr1, taxid 100000006, rank sequence
--- Strain2_Plasmid1, taxid 100000007, rank sequence
```

**Comment by PhDstuff** [comment]
Brilliant, this worked, 
I generated the .kraken file which appears to have the information I want i.e. connecting reads with certain strains and then used krakenhll-translate, however the .labels file then does not accept the new classification schemes. It appears to leave the taxonomy column blank for all those reads that were classified beyond the species level i.e. with my added strains classification. 

Additionally is there some score associated with any of the classifications?
It appears I could take some sort of measurement based on the number of kmers within the read assigned to a particular strain, omitting any reads that have had kmers mapping to multiple strains?

**Comment by fbreitwieser** [comment]
I'll fix krakenhll-translate, I personally didn't use the script before. 

The additional scores from krakenhll are the unique k-mer count and, related, the coverage of the strains k-mers in the database. In your use-case you may want to filter strains with few k-mers that are unique to them. I'd suggest looking at a couple of datasets to deduce a threshold.

**Comment by fbreitwieser** [comment]
Fixed the `--add-to-library` bugs. @PhDstuff , can you provide examples for your problems with `krakenhll-translate` ? I do not encounter them.
