### ISSUE TITLE
krakenhll-report

### ISSUE THREAD

**Issue by yi1873** [fbreitwieser/krakenhll#7]
krakenhll-report cannot get results

**Comment by fbreitwieser** [comment]
Hi @yi1873 , I'll look into it. However, please just use `krakenhll --report-file REPORT`. `krakenhll-report` does not contain any extra information on k-mer counts and coverage

**Comment by fbreitwieser** [comment]
You can do that, however you will not have the unique k-mer counts, then. That score is interesting, I will think about adding it to KrakenHLL

**Comment by yi1873** [comment]
Looking forward to your updated KrakenHLL !

**Comment by fbreitwieser** [comment]
@yi1873 , I put the score idea into a separate issue #9.
